"""fase5_1 initial persistence schema

Revision ID: 147bc9e8341e
Revises: 
Create Date: 2026-07-13 19:52:18.767144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147bc9e8341e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('subject_type', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entries_subject_id'), 'audit_log_entries', ['subject_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_subject_type'), 'audit_log_entries', ['subject_type'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('decided_by', sa.String(length=200), nullable=False),
    sa.Column('decision', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_subject_id'), 'decisions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_decisions_subject_type'), 'decisions', ['subject_type'], unique=False)
    op.create_table('territories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('budget_eur', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_territories_slug'), 'territories', ['slug'], unique=True)
    op.create_table('managed_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('territory_id', sa.Integer(), nullable=False),
    sa.Column('external_asset_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('geometry_geojson', sa.Text(), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('DETECTED', 'VERIFIED', 'ASSIGNED', 'FUNDED', 'RESOLVED', 'MONITORED', name='managedassetstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managed_assets_external_asset_id'), 'managed_assets', ['external_asset_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('triggered_rules', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ASSIGNED', 'ESCALATED', 'DISMISSED', name='alertstatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['managed_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_asset_id'), 'alerts', ['asset_id'], unique=False)
    op.create_table('field_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.Column('method', sa.String(length=64), nullable=False),
    sa.Column('verifier', sa.String(length=200), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('photo_ref', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['managed_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_verifications_asset_id'), 'field_verifications', ['asset_id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('ehs', sa.Float(), nullable=True),
    sa.Column('ndvi', sa.Float(), nullable=True),
    sa.Column('ndmi', sa.Float(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['managed_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_asset_id'), 'observations', ['asset_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('action_label', sa.String(length=200), nullable=False),
    sa.Column('cost_eur_low', sa.Float(), nullable=True),
    sa.Column('cost_eur_high', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'DONE', name='recommendationstatus'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_alert_id'), 'recommendations', ['alert_id'], unique=False)
    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'RESOLVED', name='interventionstatus'), nullable=False),
    sa.Column('budget_eur', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['managed_assets.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventions_asset_id'), 'interventions', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interventions_asset_id'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_recommendations_alert_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_observations_asset_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_field_verifications_asset_id'), table_name='field_verifications')
    op.drop_table('field_verifications')
    op.drop_index(op.f('ix_alerts_asset_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_managed_assets_external_asset_id'), table_name='managed_assets')
    op.drop_table('managed_assets')
    op.drop_index(op.f('ix_territories_slug'), table_name='territories')
    op.drop_table('territories')
    op.drop_index(op.f('ix_decisions_subject_type'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_subject_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_audit_log_entries_subject_type'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_subject_id'), table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    # ### end Alembic commands ###
